### ISSUE TITLE
Resource template

### ISSUE THREAD

**Issue by LionelJouin** [Nordix/Meridio-Operator#88]
**Is your feature request related to a problem? Please describe.**
The user should be able to modify the template of the resources deployed by the operator. Allowing the modification of these template would let user set the resource limit, pod affinity...

**Describe the solution you'd like**

TODO

**Describe alternatives you've considered**

_Alternative 1:_

Replace the resource requirement feature by this new feature. The full yaml templates (e.g. [proxy](https://github.com/Nordix/Meridio-Operator/blob/master/deployment/proxy.yaml)) could be included in the configmap (which will be injected and updated every 30s in the operator) in this format:
```
template-a.lb-fe: |-
    ...
template-a.proxy: |-
    ...
template-b.lb-fe: |-
    ...
template-b.proxy: |-
    ...
```
In the CRD, annotation could be added to select the template (template-a, template-b). The operator will then select the corresponding template file with \<annotation-value>.\<resource>. If the template file doesn't exist or is invalid, an error can be printed in the operator logs.

The locked part of the template will be only defined in the (golang) code.

_Alternative 2:_

Replace the resource requirement feature by this new feature. 
The templates have parameters in a specific format (e.g.: {{ <parameter name> }}) which will expose to the user some parts of the template. 
The value of the parameters can be configured in a configmap and selected via the annotation in the CRDs.
This solution could be very generic. So, to add a new variable, the template will only need to be adapted with the new desired variable, and the operator could detect them in the template, and find the corresponding value based on the annotation when the user will deploy a CR.

![Operator-Resource Parameterized-Template drawio](https://user-images.githubusercontent.com/1494440/171591565-8bd4fd28-cea0-4085-9cb3-bed4bf292d08.png)

**Additional context**
https://docs.google.com/presentation/d/19AF0LZwRg7WmIatmA373x0G0I7b-Emt9jAezRfbWzgA/edit?usp=sharing

**Comment by tedlean** [comment]
hmm... I think somethings has gone wrong here, or am I complete lost...?

The alternative 2 so nicely described and depicted is almost completely identical to the solutions already implemented by Zoltan.  I have recently added a similar description for this in the nVIP userguide.

This approach should only be use for making settings which is "instance specific". For example a conduit with a little amount of traffic require fewer resources than one with a large amount. 

There are also DR related settings that are pod type specific (such as all FE pod should have high priority to keep up BFD sessions) or even generic for the complete nVIP installation, that is all nVIP pod should have surden setting according to Ericsson DRs. 

Some of these settings are fixed and not to be changed. These can just be put into the "burn-in" operand templates.

But for some setting the user should be able to change specific settings on the commands line as part of the helm installation. 
Such setting needs to be exposed in the values file, (if I understand correctly) 

For nVIP operands it would not make sense having to specify a template for this kind of setting on each an every CO. 
Instead I think we should "externalize" the operand templates.
 
Either by including everything directly in the helm-chart, with values -files etc.
Or if possible only have the values-file exposed in the helm chart, so these setting can be overwritten by the helm command line.

I think I now prefer full helm chart exposure, as this will solve all problems we currently are facing. The user is not supposed to touch the helm charts and that is kind of the same for all ADP components.   

I think it should be very simple to achieve this kind of setup as it mostly is a helm exercise, right?

**Comment by LionelJouin** [comment]
Solved with https://github.com/Nordix/Meridio-Operator/pull/92
