### ISSUE TITLE
Multi-Conduit Support

### ISSUE THREAD

**Issue by LionelJouin** [Nordix/Meridio-Operator#94]
**Is your feature request related to a problem? Please describe.**
Currently, only 1 Conduit is allowed per trench and the FE and Load-balancer are thigh together in the LB-FE pod. Since an Attractor CR is triggering the deployment of the LB-FE pods, the information to configure the load-balancer container and FE containers are easy to find (in the Attractor CR + in the Conduit attached to the Attractor via the `composites` property). 

In my opinion, the LB-FE deployment should be managed by the Conduit CR instead of the Attractor CR.

**Describe the solution you'd like**
1. Move the `replicas` property from the Attractor CRD to the Conduit CRD.
2. Remove the `composites` property from the Attractor CRD.
3. Add new property (list of Attractors) in the Conduit CRD for the users to specify from where the traffic should come from (e.g. `Attractors`, `AttractedBy`...)*. 
4. Lock this new property to allow only 1 Attractor until we have the FE and Load-balancer separated.
5. Prevent the deployment of the Conduit if the Attractor doesn't exist and prevent an Attractor to be added to this new property if another Conduit is already using it.

\* Since the relation is inverted, the conduit needs to know the Attractor to fill the information required by the FE containers in the LB-FE pod.

**Describe alternatives you've considered**
/

**Additional context**
https://github.com/Nordix/Meridio/issues/238

**Comment by tedlean** [comment]
Wow... Sorry.. this is a lot of proposed changes I do not fancy ;-)

The reasoning behind the current structure is founded in the FrontEnd QS, which I have attached, No sure if you have seen this. 

[QS nVIP Front Ends.pdf](https://github.com/Nordix/Meridio-Operator/files/8916876/QS.nVIP.Front.Ends.pdf)

1. Move the replicas property from the Attractor CRD to the Conduit CRD.
When we split FE and LB in two pods we will have to re-introduce the replicas in the Attractor again, so why remove it?

2. Remove the composites property from the Attractor CRD.
The Attractor is the one that has to have node (anti)-affinity to distribute the FEs, So it has to be the Attractor/FEs that "drags along" the LB in the collocated (composite) setup.
 
3. Add new property (list of Attractors) in the Conduit CRD for the users to specify from where the traffic should come from (e.g. Attractors, AttractedBy...)*.
There should not be any hard binding between attractors and conduits. This is controlled by the mapping of streams to conduits. That is why we keep talking about eventually having a full-mesh between all Attractors and conduits. In principle any FE should be able to send traffic to any LB based on the IP-header.  Again if we introduce this proposal, it will be an NBC to remove it later.
 
4. Lock this new property to allow only 1 Attractor until we have the FE and Load-balancer separated.
It is okay to say that for now we only support a one to one mapping between attractor and conduit. But it should not be controlled by an explicit configuration, as this could ruin the possibility for changing this later.

5. Prevent the deployment of the Conduit if the Attractor doesn't exist and prevent an Attractor to be added to this new property if another Conduit is already using it.
As said above there is no hard binding between conduits and attractors, all is to be based on traffic forwarding. One conduit should be able to receive traffic from, say, three attractors and three conduits should be able to receive traffic from one attractor. It all should depend on traffic configuration. 

Note that the attractors reflects connections to external gateway and networks. The conduit reflects a network service chain the traffic should be subjected to, so finally there has to be a switch/routing function between the attractor and the conduits to ensure that traffic entering by any attractor can be handled through any conduit. 
This is final goal to aim at, so we should try to keep any interim solution/configuration options in a way that do not pave the road towards this goal with a lot of NBCs preventing us from getting there. 

L)

**Comment by tedlean** [comment]
Wow... Sorry.. this is a lot of proposed changes I do not fancy ;-)

Move the replicas property from the Attractor CRD to the Conduit CRD.
When we split FE and LB in two pods we will have to re-introduce the replicas in the Attractor again, so why remove it?

Remove the composites property from the Attractor CRD.
The Attractor is the one that has to have node (anti)-affinity to distribute the FEs, So it has to be the Attractor/FEs that "drags along" the LB in the collocated (composite) setup.

Add new property (list of Attractors) in the Conduit CRD for the users to specify from where the traffic should come from (e.g. Attractors, AttractedBy...)*.
There should not be any hard binding between attractors and conduits. This is controlled by the mapping of streams to conduits. That is why we keep talking about eventually having a full-mesh between all Attractors and conduits. In principle any FE should be able to send traffic to any LB based on the IP-header. Again if we introduce this proposal, it will be an NBC to remove it later.

Lock this new property to allow only 1 Attractor until we have the FE and Load-balancer separated.
It is okay to say that for now we only support a one to one mapping between attractor and conduit. But it should not be controlled by an explicit configuration, as this could ruin the possibility for changing this later.

Prevent the deployment of the Conduit if the Attractor doesn't exist and prevent an Attractor to be added to this new property if another Conduit is already using it.
As said above there is no hard binding between conduits and attractors, all is to be based on traffic forwarding. One conduit should be able to receive traffic from, say, three attractors and three conduits should be able to receive traffic from one attractor. It all should depend on traffic configuration.

Note that the attractors reflects connections to external gateway and networks. The conduit reflects a network service chain the traffic should be subjected to, so finally there has to be a switch/routing function between the attractor and the conduits to ensure that traffic entering by any attractor can be handled through any conduit.
This is final goal to aim at, so we should try to keep any interim solution/configuration options in a way that do not pave the road towards this goal with a lot of NBCs preventing us from getting there.

L)

**Comment by LionelJouin** [comment]
@tedlean Thank you for the clarification.
Multi-Conduit works fine with the changes in this PR: https://github.com/Nordix/Meridio-Operator/pull/95
But now users could create multiple attractors with the same conduit in the composite (which is invalid without the LB-FE separation), should we lock it in the webhook?
Same question for the VIP, if the same VIP is used by 2 (or more) conduit/attractor, there will be a problem, should it be locked in the webhook?

**Comment by tedlean** [comment]
hi
I am fine with preventing these non-working configuration options as it should be possible to lift them again without NBC issues.

Just for the record. Both problems originate in the missing "full mesh" between FEs and LBs. 
In principle this is not depending on a split of FE and LB into two pod. Eventually even if collocated with a LB, the FE should be able to forward to another LB.  The forwarding should be something like: Use local first if feasible, but if not, forward traffic to another pod instance.
The "traffic forwarding model" should be the same for both composite and non-composite. The composite is "just" an optimization, not a model, per say. 

L)
